server:
  port: 9000

spring:
  application:
    name: ms-loan
  datasource:
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5432/library}
    username: postgres
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
